# setup
setup: scan

# Loss
criterion: scan
criterion_kwargs:
   entropy_weight: 5.0
   target: [0.07, 0.17, 0.12, 0.16, 0.18, 0.05, 0.06, 0.08, 0.04, 0.08]

# Weight update
update_cluster_head_only: False # Update full network in SCAN
num_heads: 1 # Only use one head

# Model
backbone: resnet50

# Dataset
train_db_name: tobacco3482
val_db_name: tobacco3482
num_classes: 10
num_neighbors: 20

# Transformations
augmentation_strategy: ours
augmentation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.9287, 0.9287, 0.9287]
      std: [0.1568, 0.1568, 0.1568]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 32
     random: True

transformation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.9287, 0.9287, 0.9287]
      std: [0.1568, 0.1568, 0.1568]

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
epochs: 100
batch_size: 128
num_workers: 8

# Scheduler
scheduler: constant
