# Setup
setup: moco # MoCo is used here

# Model
backbone: resnet50
pretrained: ./pretrained/moco_rvl-cdip_800.pth.tar
model_kwargs:
   head: mlp
   features_dim: 128

# Dataset
train_db_name: rvl-cdip
val_db_name: rvl-cdip
num_classes: 16
temperature: 0.07
compute_negatives: True

# Batch size and workers
batch_size: 128
num_workers: 8

# Transformations
transformation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.9176, 0.9176, 0.9176]
      std: [0.1852, 0.1852, 0.1852]
